### ISSUE TITLE
Overlapping constraints over variables returns an error when using Mosek

### ISSUE THREAD

**Issue by yuwenchen95** [jump-dev/MosekTools.jl#115]
I was using Mosek via JuMP where some parts of variables are used multiple times in different conic constraints.
```julia
using LinearAlgebra, SparseArrays
using JuMP,Mosek,MosekTools
using ECOS,Clarabel
model = Model(Mosek.Optimizer)
@variable(model, p[1:5])
@variable(model,q)
@objective(model, Min, p[1])
@constraint(model, sum(p) == 1)
@constraint(model, p in MOI.SecondOrderCone(length(p)))
@constraint(model, vcat(p[4],p[5],q) in MOI.ExponentialCone())
optimize!(model)
```

It returns error 1307 in Mosek as follows:
```
MOSEK error 1307: Variable '' (4) is a member of cone '' (0).
ERROR: LoadError: MosekError(1307, "Variable '' (4) is a member of cone '' (0).")
```

However, ECOS and Clarabel don't have this issue. It looks like ECOS and Clarabel use the bridging inside MathOptInterface.jl  to transform the problem into solvers' standard form while Mosek can't. Could the incoming version of MathOptInterface.jl fix this issue?

**Comment by odow** [comment]
I've transferred this to MosekTools. It doesn't seem like an issue in MathOptInterface.

**Comment by blegat** [comment]
You cannot have variables in two different cones in Mosek. Here, the variables of `p` are both in the second-order cone and the exponential cone. Mosek is going away from the VectorOfVariables-in-cone interface to the VectorAffineConstraint-in-cone interface. They added support for the latter in Mosek v10 and will remove support for the former in a future version (probably v11 ?) so this should get fixed once this is done. At the MOI level, we don't have a way to know that the solver does not support these kind of this so that the bridges handle that. We could throw a better error message though

**Comment by yuwenchen95** [comment]
Thanks for your response. I am wondering whether incoming Mosek.jl or MosekTools can fix it using current MOI since ECOS and Clarabel don't have such kind of issue. I think they only use some internal transformation of a problem inside MOI automatically.

**Comment by odow** [comment]
> I am wondering whether incoming Mosek.jl or MosekTools can fix it using current MOI since ECOS and Clarabel don't have such kind of issue

It's probably too much work to implement this. You can work around this yourself by adding additional variables and an equality constraint. This isn't really a bug in Mosek.jl or MosekTools.jl; it matches the underlying behaviour of the Mosek solver.

**Comment by yuwenchen95** [comment]
I see. Thanks!

**Comment by blegat** [comment]
The reason why it works with ECOS and Clarabel is that they are using VectorAffineConstraint-in-cone like Mosek will do in its latter version. There is nothing special done at the MOI level in MOI or Clarabel that would help Mosek at the moment.

**Comment by yuwenchen95** [comment]
> The reason why it works with ECOS and Clarabel is that they are using VectorAffineConstraint-in-cone like Mosek will do in its latter version. There is nothing special done at the MOI level in MOI or Clarabel that would help Mosek at the moment.

Thanks for your explanation!
