### ISSUE TITLE
Feature Request: VariableBasisStatus

### ISSUE THREAD

**Issue by ma29xc** [jump-dev/MosekTools.jl#131]
In MathOptInterface (MOI) syntax I get the basis status of a variable `x` attached to a `model` via

`MOI.get(model, MOI.VariableBasisStatus(), x)`

This status should correspond to the `xxstatus` in the `MosekSolution` structure.
Unfortunately, the `MOI.VariableBasisStatus()` is currently not supported. My current workaround is to read

`model.moi_backend.optimizer.model.solutions[end].xxstatus`

which is obviously inconvenient.

If it is to much work to implement, is there a better workaround?

**Comment by blegat** [comment]
I should just be rather straightforward, the status is
https://github.com/MOSEK/Mosek.jl/blob/ea17cd2ac2f5dae43e2f9a29948ded26c3a57b7b/src/msk_enums.jl#L12375-L12390
