### ISSUE TITLE
Slow `read_from_file` for `.cbf` files containing SDP constraints

### ISSUE THREAD

**Issue by mipals** [jump-dev/MosekTools.jl#135]
Hi there,

I am currently solving a few models with PSD constraints using `MosekTools.jl`. The models are all read from .cbf files using `JuMP.read_from_file`, but there seem to be a large overhead in the reading of the models. 

As an example one the models look as follows
```julia 
julia> model_mosek
A JuMP Model
Maximization problem with:
Variables: 100750
Objective function type: AffExpr
`Vector{VariableRef}`-in-`MathOptInterface.Nonnegatives`: 1 constraint
`Vector{VariableRef}`-in-`MathOptInterface.PositiveSemidefiniteConeTriangle`: 9632 constraints
`Vector{AffExpr}`-in-`MathOptInterface.Zeros`: 3 constraints
`Vector{AffExpr}`-in-`MathOptInterface.Nonpositives`: 1 constraint
Model mode: AUTOMATIC
CachingOptimizer state: ATTACHED_OPTIMIZER
Solver name: Mosek
```

Using `@time optimize!(model_mosek)`  I get the following
```julia 
 43.853957 seconds (2.12 G allocations: 142.302 GiB, 13.44% gc time)
```
The model itself is solved in around 6 seconds, so the main issue here seem to be in the conversion of the model. 

When reading and solving the same models using Clarabel there is no overhead when reading in the `.cbf` files, which is making me think there is an issue hiding somewhere here.

**Comment by blegat** [comment]
Could you share the cbf file (or an alternative version that reproduces the issue if you have sensitive information) ?
