### ISSUE TITLE
Zero ConstraintPrimal and ConstraintDual for SDP constraint

### ISSUE THREAD

**Issue by blegat** [jump-dev/MosekTools.jl#14]
I cannot reproduce it locally, similar to https://github.com/JuliaOpt/MosekTools.jl/issues/1
See https://travis-ci.org/JuliaOpt/MosekTools.jl/jobs/499327096#L512-L700

**Comment by blegat** [comment]
@ulfworsoe Could you take a look at this ? It would be helpful to have Travis tests passing.

**Comment by ulfworsoe** [comment]
I'll have a look. I suspect it is probably caused by the tests using solve.mosek.com instead of a local server.

**Comment by ulfworsoe** [comment]
I can confirm that it is an underlying problem related to communication with the opt-server. It has to be fixed in Mosek, and I don't know when I'll have a fix ready. I'll close the ticket when it works.

**Comment by blegat** [comment]
@ulfworsoe Thanks, CI is passing now, this seems to have been fixed!

**Comment by ulfworsoe** [comment]
I can't close issues, but https://github.com/jump-dev/MosekTools.jl/pull/86 should update tests so all use the optserver,

**Comment by odow** [comment]
Closing because this issues seems to be fixed.
