### ISSUE TITLE
Large number of nonzeros in (very sparse) SDP solving

### ISSUE THREAD

**Issue by angeris** [jump-dev/MosekTools.jl#54]
Heya MosekTools team!

I've been running into a problem with Mosek (similar to the one given in #40): when solving a very sparse SDP, the number of nonzeros that I've been running into has been huge. For example, here's a simple problem (with optimal value 0):
```julia
using MosekTools, JuMP, SparseArrays, LinearAlgebra

m = Model(Mosek.Optimizer)

n = 100

@variable(m, x[1:100])
@variable(m, t)

@objective(m, Min, t)
Q = [
    sparse([t])     x'
    x               sparse(I(n))
]
@constraint(m, Q ∈ PSDCone())

optimize!(m)
```

Running this, we get:
```
Presolve terminated. Time: 0.00    
Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 5151            
  Cones                  : 0               
  Scalar variables       : 101             
  Matrix variables       : 1               
  Integer variables      : 0               

Optimizer  - threads                : 4               
Optimizer  - solved problem         : the primal      
Optimizer  - Constraints            : 5151
Optimizer  - Cones                  : 1
Optimizer  - Scalar variables       : 102               conic                  : 102             
Optimizer  - Semi-definite variables: 1                 scalarized             : 5151            
Factor     - setup time             : 2.18              dense det. time        : 0.00            
Factor     - ML order time          : 1.43              GP order time          : 0.00            
Factor     - nonzeros before factor : 1.33e+07          after factor           : 1.33e+07        
Factor     - dense dim.             : 0                 flops                  : 4.57e+10    
```

The problem here is specifically `Factor     - nonzeros before factor : 1.33e+07` (!). The number of nonzeros here should be something like 3n + 1. In fact, this is so large, I'm not even sure where this number could come from! (Certainly even concretizing the whole matrix `Q` yields only a total number of `101^2` nonzeros. There are probably some additional affine constraints in the cone embedding, I'm sure, but still.)

Additionally, comparing the number of nonzeros with something like `COSMO.jl` is many times larger than presented. (E.g., I think this might rule out the issue that JuMP/MOI is not correctly handling sparsity, but I could be wrong.)

Anyways, it would be extraordinarily helpful to be able to solve these big SDPs using a relatively robust interior point method, so I'd love to know if I'm doing something wrong here :)

Thanks!

**Comment by blegat** [comment]
Note sure what this `Factor - nonzeros before factor` means and why it is so large.
Note that Mosek does not support PSD constraints and it is reformulated as a PSD variables. Therefore, you don't need to create free variables `t` and `x`, you can just take it from `Q`. For instance, you can do:
```julia
using MosekTools, JuMP

m = Model(Mosek.Optimizer)

n = 100

@variable(m, Q[1:(n + 1), 1:(n + 1)], PSD)
t = Q[1, 1]
x = Q[1, 2:(n + 1)]
for j in 2:n
    for i in 2:j
        if i == j
            @constraint(m, Q[i, j] == 1)
        else
            @constraint(m, Q[i, j] == 0)
        end
    end
end

@objective(m, Min, t)

optimize!(m)
```
However, I still have a lot of nonzeros before factor:
```
Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 4950            
  Cones                  : 0               
  Scalar variables       : 0               
  Matrix variables       : 1               
  Integer variables      : 0               

Optimizer started.
Presolve started.
Linear dependency checker started.
Linear dependency checker terminated.
Eliminator started.
Freed constraints in eliminator : 0
Eliminator terminated.
Eliminator - tries                  : 1                 time                   : 0.00            
Lin. dep.  - tries                  : 1                 time                   : 0.00            
Lin. dep.  - number                 : 0               
Presolve terminated. Time: 0.00    
Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 4950            
  Cones                  : 0               
  Scalar variables       : 0               
  Matrix variables       : 1               
  Integer variables      : 0               

Optimizer  - threads                : 4               
Optimizer  - solved problem         : the primal      
Optimizer  - Constraints            : 4950
Optimizer  - Cones                  : 0
Optimizer  - Scalar variables       : 0                 conic                  : 0               
Optimizer  - Semi-definite variables: 1                 scalarized             : 5151            
Factor     - setup time             : 1.39              dense det. time        : 0.00            
Factor     - ML order time          : 0.99              GP order time          : 0.00            
Factor     - nonzeros before factor : 1.23e+07          after factor           : 1.23e+07        
Factor     - dense dim.             : 0                 flops                  : 4.05e+10        
ITE PFEAS    DFEAS    GFEAS    PRSTATUS   POBJ              DOBJ              MU       TIME  
0   0.0e+00  1.0e+00  2.0e+00  0.00e+00   1.000000000e+00   0.000000000e+00   1.0e+00  1.39  
1   0.0e+00  0.0e+00  0.0e+00  1.00e+00   0.000000000e+00   0.000000000e+00   0.0e+00  2.38  
Optimizer terminated. Time: 2.39
```

cc @erling-d-andersen

**Comment by erling-d-andersen** [comment]
MOSEK has no auto dualizer for SDPs. That means if your problem is really on LMI form you should formulate on dual form if you care about efficiency.

In other words you should study what is Mosek primal form and make sure the problem you input fits that.

Mosek may get more clever about this in the future.

**Comment by blegat** [comment]
For the dualization, we have a solver-independent solution in https://github.com/jump-dev/Dualization.jl

**Comment by erling-d-andersen** [comment]
For now does not that solve the problem?

I mean if solve the dual problem then Mosek should work efficiently.

**Comment by angeris** [comment]
It does indeed solve the problem in this (particular) scenario! Thanks. More generally, I do wonder why Mosek does not generally recognize chordal SDP sparsity patterns? This seems like it would be huge for general SDPs!

(On the other hand, it would also be great if there was an MOI bridge for chordally sparse SDPs which automatically would convert such problems to the appropriate form. I think I'll make a script that does something similar, but it would probably need to have plenty of work to be added as an MOI bridge and recognized by JuMP correctly.)

**Comment by erling-d-andersen** [comment]
We do not recognize chordal structure. There are no plans to add such a feature Mosek any time soon.

**Comment by blegat** [comment]
There is chordal sparsity reduction implemented in https://github.com/jump-dev/SumOfSquares.jl/, you should use
```julia
using DynamicPolynomials, SumOfSquares
@polyvar x[1:n]
@constraint(model, x' * Q * x in SOSCone(), sparsity = VariableSparsity())
```
Instead of
```julia
@constraint(model, Q in PSDCone())
```

**Comment by angeris** [comment]
Phenomenal! This would be absolutely amazing! I'll take a look! :)
