### ISSUE TITLE
Mosek.Optimizer is not an MOI.AbstractOptimizer

### ISSUE THREAD

**Issue by ianfiske** [jump-dev/MosekTools.jl#59]
This isn't really a bug, but more that it causes unexpected behavior elsewhere.  This came up in https://github.com/focusenergy/LinearFractional.jl/pull/16.  Do we require solvers that implement the MOI interface to inherit from MOI.AbstractOptimizer?

**Comment by odow** [comment]
Yes, this is a bug.

**Comment by blegat** [comment]
Just legacy reason, @ulfworsoe called it that way before we had the convention, I guess we can rename it.

**Comment by ulfworsoe** [comment]
Things have moved quite a bit since the first implementation I made, I don't any reasons for design decisions I made back then are still valid. Would it cause explosions all round if `MosekModel` was called `Optimizer` and was given a constructor compatible with the current `Optimizer` function?

**Comment by blegat** [comment]
I don't think that it would cause too many issues, we can bump the minor release in case someone relied on that

**Comment by odow** [comment]
Closed by https://github.com/jump-dev/MosekTools.jl/pull/68
