### ISSUE TITLE
Generated cuts at MIP root node not passed down

### ISSUE THREAD

**Issue by hassanis** [jump-dev/MosekTools.jl#60]
Hello,
I’m working on a problem using Mosektools & JUMP. It seems that after running it heuristics and cut generation at the root node, it fails to add them to the problem. As you can see in the output below, the relaxation objective isn’t modified based on the lower bound found at the root node:
```
BRANCHES RELAXS   ACT_NDS  DEPTH    BEST_INT_OBJ         BEST_RELAX_OBJ       REL_GAP(%)  TIME  
0        1        1        0        NA                   5.8931608812e-07     NA          0.0   
0        1        1        0        1.2255160232e-06     5.8931608812e-07     51.91       0.1   
0        1        1        0        6.5593301415e-07     5.8931608812e-07     10.16       0.1   
Cut generation started.
0        1        1        0        6.5593301415e-07     5.9350413814e-07     9.52        0.2   
Cut generation terminated. Time = 0.00
10       14       11       3        6.5593301415e-07     5.3101616733e-07     19.04       0.4   
24       28       23       6        6.5593301415e-07     5.3101616733e-07     19.04       0.5 
```

As you can see, at the root node the lower bound is improved to a relative gap of 9.52%, but the jumps back up to 19.04%.
Best,
H.

**Comment by hassanis** [comment]
Here's the output of another input. Something strange is happening at the root node:

```
BRANCHES RELAXS   ACT_NDS  DEPTH    BEST_INT_OBJ         BEST_RELAX_OBJ       REL_GAP(%)  TIME  
0        1        1        0        NA                   5.6239158371e-07     NA          0.1   
0        1        1        0        6.0735825854e-07     5.6239158371e-07     7.40        0.1   
0        1        1        0        6.0500666035e-07     5.6239158371e-07     7.04        0.2   
Cut generation started.
0        1        1        0        6.0500666035e-07     5.2770718671e-07     12.78       0.3   
Cut generation terminated. Time = 0.00
10       14       11       5        6.0500666035e-07     5.6062054405e-07     7.34        0.5   
26       30       27       8        6.0500666035e-07     5.6062054405e-07     7.34        0.6
```

**Comment by blegat** [comment]
You will probably get more help by directly asking mosek support. This repository is mainly about the implementation of [MathOptInterface](https://github.com/jump-dev/MathOptInterface.jl) for Mosek and this does not seem to be related to the interface.

**Comment by odow** [comment]
Closing because this isn't a bug in MosekTools. Please contact Mosek support for advice. 

(MosekTools.jl is maintained by the JuMP community; Mosek.jl is maintained my Mosek proper.)
