### ISSUE TITLE
Conic reformulation of nonlinear terms in Mosek

### ISSUE THREAD

**Issue by miladdf94** [jump-dev/MosekTools.jl#61]
Hi @mlubin @BenChung @blegat @odow @chriscoey 

I am new to conic programming using Mosek. 
I am trying to reformulate a model into conic programming, and then I would need to solve it using Mosek/MosekTools.
Based on the definition of the exponential cone see [here](https://docs.mosek.com/modeling-cookbook/expo.htmll), a constraints like x*e^(y/x) <= t can be represented as ( t, x , y) \in K_exp.

However, I have faced the following constraint in **a part of my model**:

(c1):    x*e^y <= t  (where x >=0)

My question is: How can I represent this constraint (non-convex)?

It seems Mosek cannot handle such a constraint. Is there any other solver that could address this issue?
Any suggestion would be appreciated.

**Comment by ulfworsoe** [comment]
I'm not sure this is the right place for the question, but I don't think you can model this with the cones supported by Mosek. 

My guess is that you would have to use a general non-linear, non-convex solver.

**Comment by odow** [comment]
You should try Ipopt.jl instead.

I'm going to close this issue because the JuMP community forum is a more appropriate place for these questions: https://discourse.julialang.org/c/domain/opt/13. Please post there if you have further questions.
