### ISSUE TITLE
MOSEK: support to MOI.FEASIBILITY_SENSE?

### ISSUE THREAD

**Issue by ds2010** [jump-dev/MosekTools.jl#62]
Hi all, 

I am now using the Julia/MosekTools to solve the quadratic programming (QP) problem. I encountered the following error:

`ERROR: LoadError: ArgumentError: Objective bridge of type MathOptInterface.Bridges.Objective.SlackBridge{Float64,MathOptInterface.ScalarQuadraticFunction{Float64},MathOptInterface.ScalarQuadraticFunction{Float64}} does not support modifying the objective sense. As a workaround, set the sense to MOI.FEASIBILITY_SENSE to clear the objective function and bridges.`

My objective function is `sum(y_i-phi_i)^2`, where `y` is given data (parameter) and `phi` is the decision variable. So, I would like to know how to fix this issue. Could you please give me some suggestions? Many thanks in advance!

**Comment by ulfworsoe** [comment]
MosekTools is only the underlying solver API for Mosek. I think this is probably something you should ask about at https://github.com/jump-dev/MathOptInterface.jl/

**Comment by ds2010** [comment]
OK. I got! Thnak you!

**Comment by odow** [comment]
@ds2010 make a small reproducible example, and post it on the [Community Forum](https://discourse.julialang.org/c/domain/opt/13).
