### ISSUE TITLE
Preparing for MOSEK 10

### ISSUE THREAD

**Issue by ulfworsoe** [jump-dev/MosekTools.jl#64]
In MOSEK 10 we will make some API additions and some deprecations that are relevant to MathOptInterface. Most importantly we are deprecating variable-in-cone bounds and introducing constraints of the form `Ax+b in K`, and we are adding a few cone types. 

The summay:
* Deprecated: VectorOfVariables in cone
* Unchanged:  VectorOfVariables in PSD cone
* New: VectorAffineFunction in cone (including linearized PSD cone)

@blegat I will probably need some advice on what to add and remove.

**Comment by blegat** [comment]
About the deprecation, what do we do ? Do we keep the support in the MOI wrapper so that the user see the MOSEK warning ? So we don't need to do anything for that part.
For the `VectorAffineFunction`, we'll need to do
```julia
MOI.supports_constraint(::MosekModel, ::Type{MOI.VectorAffineFunction{Float64}}, ::Type{<:VectorCone}) = true
MOI.supports_constraint(::MosekModel, ::Type{MOI.VectorAffineFunction{Float64}}, ::Type{MOI.PositiveSemidefiniteConeTriangle}) = true
function MOI.add_constraint(model::MosekModel, func::MOI.VectorAffineFunction{Float64}, set::VectorCone)
    # Add the constraint to the Mosek model
    return MOI.ConstraintIndex{typeof(func), typeof(set)}(
        # Some index that makes it easy to map to the corresponding Mosek indices
        # Preferably without the need for any map stored in the MosekModel
        # The indices can be the same for different type of sets, it only need to be unique for indices of the same set
    )
end
function MOI.add_constraint(model::MosekModel, ::Type{MOI.VectorAffineFunction{Float64}}, ::Type{MOI.PositiveSemidefiniteConeTriangle})
    # Add the constraint to the Mosek model
    return MOI.ConstraintIndex{typeof(func), typeof(set)}(
        # Some index that makes it easy to map to the corresponding Mosek indices
        # Preferably without the need for any map stored in the MosekModel
        # The indices can be the same than for the `VectorCone`
    )
end
```
Is there some documentations somewhere on the new API ?

**Comment by ulfworsoe** [comment]
Wrt. deprecation: The deprecated functions will stick around for version 10.x and most likely be eliminated en 11, so there is no hurry.

There is no alpha out yet and no public documentation, but the basic idea is to add rows of form /ax+b/, then add a constraint consisting of a set of row indexes and a domain. It can be done with minimal additions to the existing implementation - the functions you mention plus some book-keeping for the affine expressions.

Is a dynamic check for version the best way to do it? What would happen when `add_constraint()` mentions functions not defined in MOSEK 9?

**Comment by blegat** [comment]
> the basic idea is to add rows of form /ax+b/, then add a constraint consisting of a set of row indexes and a domain. It can be done with minimal additions to the existing implementation - the functions you mention plus some book-keeping for the affine expressions.

I see, so these will share the same index space as rows of linear constraints ?

> Is a dynamic check for version the best way to do it? What would happen when `add_constraint()` mentions functions not defined in MOSEK 9?

We should add a
```julia
if Mosek.getversion(mosek.task)[1] >= 10
    throws(MOI.UnsupportedConstraint{typeof(func),typeof(set)}())
end
```
at the beginning of the two `add_constraint` methods too indeed.

**Comment by ulfworsoe** [comment]
> > the basic idea is to add rows of form /ax+b/, then add a constraint consisting of a set of row indexes and a domain. It can be done with minimal additions to the existing implementation - the functions you mention plus some book-keeping for the affine expressions.
> 
> I see, so these will share the same index space as rows of linear constraints ?
No. The Linear constraints remain unchanged and unaffected. The rows for affine conic constraints are stored separately and have their own indexing. We have to be able to delete and reuse affine rows, but that is what we already do with variables.
> 
> > Is a dynamic check for version the best way to do it? What would happen when `add_constraint()` mentions functions not defined in MOSEK 9?
> 
> We should add a
> 
> ```julia
> if Mosek.getversion(mosek.task)[1] >= 10
>     throws(MOI.UnsupportedConstraint{typeof(func),typeof(set)}())
> end
> ```
> 
> at the beginning of the two `add_constraint` methods too indeed.
I mean, something like a compile-time (or load-time) if-statement, if we had a global version constant defined in the Mosek API (which I just noticed that we don't), 
```
if Mosek.MAJORVER >= 10
  function MOI.add_constraint(...) ... end
end
```
would that work and be defined in the global scope?

**Comment by blegat** [comment]
> ```
> if Mosek.MAJORVER >= 10
>   function MOI.add_constraint(...) ... end
> end
> ```
> 
> would that work and be defined in the global scope?

Note sure. What would happens if Julia precompiles MosekTools.jl and then the user changes binary pointed to by Mosek.jl ? I guess Julia might not execute this again. I'd feel more convortable doing this check in `add_constraint `. Anyway, if we don't define this method, the fallback is to throw `UnsupportedConstraint` and that's what we do.

**Comment by ulfworsoe** [comment]
This module would have to use functions and constants from the `Mosek` --- wouldn't that force a recompilation if Mosek is updated? I will have to read up on this.

When running this
```
using MathOptInterface
const MOI = MathOptInterface
const MOIT = MOI.Test
const MOIU = MOI.Utilities
const MOIB = MOI.Bridges
const FALLBACK_URL = "mosek://solve.mosek.com:30080"
using MosekTools
const optimizer = Mosek.Optimizer(fallback = FALLBACK_URL)
const bridged = MOIB.full_bridge_optimizer(optimizer, Float64)
model = MOIB.full_bridge_optimizer(Mosek.Optimizer(), Float64)
MOIT.copytest(bridged, model)
```
I get this error that I can't figure out:
```
ERROR: LoadError: MethodError: Cannot `convert` an object of type 
  MathOptInterface.ConstraintIndex{MathOptInterface.VectorAffineFunction,MathOptInterface.Nonpositives{}} to an object of type 
  MathOptInterface.ConstraintIndex{MathOptInterface.VectorAffineFunction{Float64},MathOptInterface.Nonpositives{}}
Closest candidates are:
  convert(::Type{T}, ::T) where T at essentials.jl:171
  MathOptInterface.ConstraintIndex{MathOptInterface.VectorAffineFunction{Float64},MathOptInterface.Nonpositives}(::Any) where {F, S} at /home/ulfw/.julia/packages/MathOptInterface/5WwpK/src/indextypes.jl:20
Stacktrace:
 [1] MathOptInterface.Bridges.Constraint.NonnegToNonposBridge{Float64,MathOptInterface.VectorAffineFunction{Float64},MathOptInterface.VectorOfVariables}(::MathOptInterface.ConstraintIndex{MathOptInterface.VectorAffineFunction,MathOptInterface.Nonpositives}) at /home/ulfw/.julia/packages/MathOptInterface/5WwpK/src/Bridges/Constraint/flip_sign.jl:139
 [2] bridge_constraint(::Type{MathOptInterface.Bridges.Constraint.NonnegToNonposBridge{Float64,MathOptInterface.VectorAffineFunction{Float64},MathOptInterface.VectorOfVariables}}, ::MathOptInterface.Bridges.LazyBridgeOptimizer{MosekModel}, ::MathOptInterface.VectorOfVariables, ::MathOptInterface.Nonnegatives) at /home/ulfw/.julia/packages/MathOptInterface/5WwpK/src/Bridges/Constraint/set_map.jl:11
 [3] add_bridged_constraint(::MathOptInterface.Bridges.LazyBridgeOptimizer{MosekModel}, ::Type{T} where T, ::MathOptInterface.VectorOfVariables, ::MathOptInterface.Nonnegatives) at /home/ulfw/.julia/packages/MathOptInterface/5WwpK/src/Bridges/bridge_optimizer.jl:1271
 [4] add_constraint(::MathOptInterface.Bridges.LazyBridgeOptimizer{MosekModel}, ::MathOptInterface.VectorOfVariables, ::MathOptInterface.Nonnegatives) at /home/ulfw/.julia/packages/MathOptInterface/5WwpK/src/Bridges/bridge_optimizer.jl:1343
 [5] copytest(::MathOptInterface.Bridges.LazyBridgeOptimizer{MosekModel}, ::MathOptInterface.Bridges.LazyBridgeOptimizer{MosekModel}) at /home/ulfw/.julia/packages/MathOptInterface/5WwpK/src/Test/modellike.jl:791
 [6] top-level scope at /home/ulfw/Projects/mosekafejl/test.jl:13
 [7] include(::Function, ::Module, ::String) at ./Base.jl:380
 [8] include(::Module, ::String) at ./Base.jl:368
 [9] exec_options(::Base.JLOptions) at ./client.jl:296
 [10] _start() at ./client.jl:506
in expression starting at /home/ulfw/Projects/mosekafejl/test.jl:13
```
