### ISSUE TITLE
Some nonlinear cone constraints do not appear in MOI.ListOfConstraints

### ISSUE THREAD

**Issue by mtanneau** [jump-dev/MosekTools.jl#69]
Exponential and power cone constraints are not returned when querying the `MOI.ListOfConstraints` attribute

For instance, 
```julia
model = Mosek.Optimizer()

x = MOI.add_variables(model, 3)
MOI.add_constraint(model, MOI.VectorOfVariables(x), MOI.ExponentialCone())

MOI.get(model, MOI.ListOfConstraints())  # returns `Tuple{DataType, DataType}[]`
```

Peeking at the MOI wrapper code, it looks like the culprit is here:
https://github.com/jump-dev/MosekTools.jl/blob/4cda47c539b80f3ea5d29a4c3117289f9a290b91/src/attributes.jl#L215-L219

Given that the latest release and current `master` branch are for Mosek v9, would it make sense to re-enable the above?

**Comment by blegat** [comment]
Yes, we should uncomment those
