### ISSUE TITLE
Why Mosek can not resolve new model when the added new constraints include SOCP constraints?

### ISSUE THREAD

**Issue by elated-sawyer** [jump-dev/MosekTools.jl#70]
Here is a mini-case of my mathematical model.
First, solve the initial model, and check if the solution meets the condition. If it does not, the new constraints will be added, and solve the new model. 
But there are some problems in this process:
1. Use Mosek as solver, when only add linear constraints (Con1), the new model can be solved, and the final optimal value is 0.5;
2. Use Mosek as solver, when the adding constraints include SOCP constraints (Con2), Mosek won’t resolve the new model, it will just keep the solution of initial model (the optimal value of initial model is 1).
3. Use other solvers, e.g. Gurobi, when the adding constraints include SOCP constraints, the new model can be solved, and the final optimal value is about 0.25.

In conclusion, Mosek can not resolve the new model, when the added new constraints include SOCP constraints.

```
using JuMP, MosekTools, Gurobi

model = Model(Gurobi.Optimizer)
#model = Model(Mosek.Optimizer)

@variable(model, x)
@variable(model, y)
@objective(model, Max, x)
@constraint(model, x <= 1)
@constraint(model, y <= 1)
optimize!(model)
println("objective value:", objective_value(model))

#check if we need to add new constraints
x_val = value.(x)
if x_val >=0.5
    @constraint(model, x <= 0.5) #Con1
    @constraint(model, [y; 4x] in SecondOrderCone()) #Con2
end
optimize!(model) 
println("objective value:", objective_value(model))
```
Could someone give me some ideas on how this problem comes? And how to solve the problem?
Thanks!

P.S. the problem has also been posted on Discourse
[https://discourse.julialang.org/t/why-mosek-can-not-resolve-new-model-when-the-added-new-constraints-include-socp-constraints/64411?u=sawyer_zhou](url)

**Comment by elated-sawyer** [comment]
Hi, there. I think I figure out how the problem comes. It seems that it is mainly due to the usage feature of Mosek. If we want to add different type of constraints, and solve the model iteratively with Mosek, we should declare the type of constraints we would like to add in the initial model. 

And I have introduced this in detail in the following link, 
[https://discourse.julialang.org/t/why-mosek-can-not-resolve-new-model-when-the-added-new-constraints-include-socp-constraints/64411?u=sawyer_zhou](url)

**Comment by blegat** [comment]
I'd still consider that it's a but, Mosek shouldn't silently ignore the constraint. @ulfworsoe Is this an expected behavior of Mosek ? Should we do anything special in this package ?
@elated-sawyer In the future, don't post the same question both on Discourse and Github, or if you do, cross-reference in each post to make sure 2 different people don't spend time answering the same questions.

**Comment by elated-sawyer** [comment]
> Thanks for reporting this confusing behavior. I'd still consider that it's a bug so let's leave this issue open, Mosek shouldn't silently ignore the constraint. @ulfworsoe Is this an expected behavior of Mosek ? Should we do anything special in this package ?
> @elated-sawyer In the future, don't post the same question both on Discourse and Github, or if you do, cross-reference in each post to make sure 2 different people don't spend time answering the same questions.

Got it, sorry about that. The cross-reference has been added

**Comment by ulfworsoe** [comment]
Is is due to a bit of previously undefined behaviour in Mosek: If a solve call doesn't overwrite a previously defined solution, it sticks around, and I think that is why you get the wrong objective. As far as I can see it changes the model correctly, and produces the correct solution, but reports the wrong one.

The PR above should fix this.
