### ISSUE TITLE
Update to MOI 0.10

### ISSUE THREAD

**Issue by odow** [jump-dev/MosekTools.jl#73]
We recently released MOI 0.10. There are a lot of changes to make: https://jump.dev/MathOptInterface.jl/dev/release_notes/#v0.10.0-(September-6,-2021)

The good news is that we're close to a 1.0 release for JuMP so this is likely the last time there will be breakage: https://github.com/jump-dev/JuMP.jl/issues/2564

**Comment by matbesancon** [comment]
started in #75

**Comment by blegat** [comment]
Closed by https://github.com/jump-dev/MosekTools.jl/pull/75#event-5439357246
