### ISSUE TITLE
Issues Precompiling MosekTools.jl

### ISSUE THREAD

**Issue by MathiasPBerger** [jump-dev/MosekTools.jl#94]
Dear MosekTools developers,

I have been experimenting with MosekTools lately and came across some unexpected precompilation issues. In short, I am unable to import the package (precompilation never stops) when creating a new environment or installing it into the default project of a new Julia release. I have so far encountered this issue with Julia 1.4, 1.5, 1.6 and 1.7, with the most recent versions of MosekTools corresponding to each release and MosekTools v0.9.3 (I did not test versions in between). The only situation in which the package works is in my old Julia 1.4 default project, where the package was pre-compiled a while back and is not pre-compiled again upon import.

Please find attached a screenshot of one of the configurations I was testing. The issue seems so weird that I suspect I am doing something wrong. I can't exactly figure out what, unfortunately, and any help or suggestion would be much appreciated.

I look forward to hearing from you,

Best regards,

Mathias Berger

<img width="1099" alt="MosekTools_precompilation" src="https://user-images.githubusercontent.com/41972972/160528793-7d097c88-0cb6-4f59-8464-49e9243f2c05.png">

**Comment by odow** [comment]
Try deleting `~/.julia/compiled`. You may have terminated Julia mid-precompilation at one point that left things in a weird state.

If that doesn't work, you can try the nuclear option of deleting `~/.julia`, but you'll need to re-download a lot of stuff when you re-instantiate the `Project.toml`.

Also, please update to at least Julia 1.6 and the latest versions.

**Comment by MathiasPBerger** [comment]
Hi Oscar, thank you for your help and this super quick answer (as always!). I cleaned up the compiled folder as you suggested (only for Julia 1.6, I assume there shouldn't be any interaction between Julia versions?) and started from an empty default project.

The issue seems to come from Mosek.jl and not MosekTools.jl proper (see attached screenshot). Interestingly, the compiled folder for Mosek.jl remains empty (no .ji file at all, not even a broken one). I'm gonna try to investigate that a little bit and see if something in my Mosek configuration prevents it from precompiling the package properly. It worked fine a while back (I see that the .ji file for Julia 1.4/Mosek v1.1.3, which I alluded to in my previous comment, was generated in September 2020), so I might have changed something that broke it since then.

<img width="1091" alt="Mosek_precompilation" src="https://user-images.githubusercontent.com/41972972/160651073-b4f871a8-d025-4b88-9649-70bd052b88bf.png">

**Comment by MathiasPBerger** [comment]
The issue indeed comes from Mosek.jl and not MosekTools.jl. I was able to precompile MosekTools v0.12.1 with Mosek v1.1.3 and import it (but not with Mosek v1.2.0), so I'll close this issue. Thank you @odow for your help.

**Comment by odow** [comment]
Nope. I'm not aware of a reason that this could happen, and there's nothing suspicious in the diff: https://github.com/MOSEK/Mosek.jl/compare/v1.1.3...v1.2.0. 

My guess is that it's probably something else in their environment. All I can suggest is that @MathiasPBerger does a clean install of Julia.

**Comment by MathiasPBerger** [comment]
Dear Oscar and Ulf,

Thank you for looking into the matter again. I agree that there's probably something wrong with my environment. Re-installing Julia completely is not that convenient at the moment so I'll stick with Mosek v1.1.3 (which currently does the job for my application) for now and let you know if re-installing Julia fixes it later.

Best,

Mathias
